# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(150, 176)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(150, 176))
        MainWindow.setMaximumSize(QtCore.QSize(150, 176))
        MainWindow.setWindowTitle("VotingApp")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ID_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ID_Label.setObjectName("ID_Label")
        self.gridLayout.addWidget(self.ID_Label, 1, 0, 1, 1)
        self.ID_Entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_Entry.setObjectName("ID_Entry")
        self.gridLayout.addWidget(self.ID_Entry, 1, 1, 1, 1)
        self.candidate_Radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate_Radio.setObjectName("candidate_Radio")
        self.radio_Group = QtWidgets.QButtonGroup(MainWindow)
        self.radio_Group.setObjectName("radio_Group")
        self.radio_Group.addButton(self.candidate_Radio)
        self.gridLayout.addWidget(self.candidate_Radio, 3, 1, 1, 1)
        self.candidate2_Radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate2_Radio.setObjectName("candidate2_Radio")
        self.radio_Group.addButton(self.candidate2_Radio)
        self.gridLayout.addWidget(self.candidate2_Radio, 4, 1, 1, 1)
        self.candidates_Label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.candidates_Label.sizePolicy().hasHeightForWidth())
        self.candidates_Label.setSizePolicy(sizePolicy)
        self.candidates_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.candidates_Label.setObjectName("candidates_Label")
        self.gridLayout.addWidget(self.candidates_Label, 2, 0, 1, 2)
        self.title_Label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_Label.sizePolicy().hasHeightForWidth())
        self.title_Label.setSizePolicy(sizePolicy)
        self.title_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_Label.setObjectName("title_Label")
        self.gridLayout.addWidget(self.title_Label, 0, 0, 1, 2)
        self.about_Label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_Label.sizePolicy().hasHeightForWidth())
        self.about_Label.setSizePolicy(sizePolicy)
        self.about_Label.setText("")
        self.about_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.about_Label.setObjectName("about_Label")
        self.gridLayout.addWidget(self.about_Label, 5, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 150, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.ID_Label.setText(_translate("MainWindow", "ID"))
        self.candidate_Radio.setText(_translate("MainWindow", "1"))
        self.candidate2_Radio.setText(_translate("MainWindow", "2"))
        self.candidates_Label.setText(_translate("MainWindow", "Candidates"))
        self.title_Label.setText(_translate("MainWindow", "Voting Application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
